services:
  postgres:
    environment:
      POSTGRES_USER: $SPRING_DATASOURCE_USERNAME
      POSTGRES_PASSWORD: $SPRING_DATASOURCE_PASSWORD
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
  database:
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: on-failure
volumes:
  postgres_data: