services:
  postgres:
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
  postgres_data: