server:
  port: 443
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=256
  jackson:
    default-property-inclusion: NON_EMPTY
  jpa:
    generate-ddl: true
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 64MB