server:
  port: 443
spring:
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=128
  jackson:
    default-property-inclusion: NON_EMPTY
  jpa:
    generate-ddl: true
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 64MB