server:
  port: 443
spring:
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=64
  jpa:
    generate-ddl: true
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 64MB